version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - cd docs && python prepare_importlib_metadata_inv.py


sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
