name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Python ${{ matrix.python }}
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13-dev']
    steps:
      - uses: actions/checkout@v4
      - name: setup test environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: install pip
        run:
          python -m pip install --upgrade pip wheel
      - name: install package
        run:
          python -m pip install .[dev]
      - name: test
        run: 
          python -m unittest discover --verbose --start-directory tests/
      - name: lint
        run:
          flake8
      - name: mypy
        run:
          mypy --strict piplicenses_lib/ tests/
      - name: codespell
        run:
          codespell
